#!/system/bin/sh

case $1 in
ro)
    echo "Enabling read-only access to /system"
    /system/bin/mount -o remount,ro /system
  ;;
rw)
  echo "Enabling read/write access to /system"
  /system/bin/mount -o remount,rw /system
  ;;
*)
    echo "Invalid or no input. Try: 'remount rw' or 'remount ro'"
  ;;
esac
